2502004102 - Musyaffa Ayman Rafif

Text Mining (LB09)

# 1. Notebook Preparation

## 1.1. Import Libraries

In [2]:
import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize

# For One Hot Encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# For Count Vectonizer
from sklearn.feature_extraction.text import CountVectorizer

## 1.2. Setup Modules

In [3]:
def text_cleansing(df):
    df_clean=df.str.lower()
    df_clean=[re.sub(r"\d+","",i )for i in df_clean]
    df_clean=[re.sub(r'[^\w]', ' ', i)for i in df_clean]
    df_clean=[re.sub(r'\s+',' ',i)for i in df_clean]
    return df_clean
    

# 2. Data Preparation

In [4]:
import pandas as pd

text1 = "THE FIRST UNSEEDED WINNER OF THE WIMBLEDON WOMEN'S SINGLES TITLE! 🏆Marketa Vondrousova has shocked the world and beaten Ons Jabeur! 👑#Vondrousova #Tennis #Wimbledon @bbcsport"
text2 = "The morning sun filtered between the tree trunks of the dense, mist-filled Chocó Cloud Forest as I watched colourful butterflies and vibrant tanagers flutter among the branches – all from the comfort of my bed with just a glass wall separating me and the outside world. Words like 'immersive' and 'eco-tourism' are often overused in the travel industry, but Mashpi Lodge, a boutique hotel placed in the middle of a steamy Ecuadorian jungle, couldn't be truer of these concepts."


In [5]:
data = {'Texts': [text1, text2]}
df = pd.DataFrame(data)

In [6]:
df.head()

Texts
0  THE FIRST UNSEEDED WINNER OF THE WIMBLEDON WOM...
1  The morning sun filtered between the tree trun...

## 2.1. Text Cleansing

Before:

In [17]:
for i in df['Texts']:
    print(i, '\n')

THE FIRST UNSEEDED WINNER OF THE WIMBLEDON WOMEN'S SINGLES TITLE! 🏆Marketa Vondrousova has shocked the world and beaten Ons Jabeur! 👑#Vondrousova #Tennis #Wimbledon @bbcsport 

The morning sun filtered between the tree trunks of the dense, mist-filled Chocó Cloud Forest as I watched colourful butterflies and vibrant tanagers flutter among the branches – all from the comfort of my bed with just a glass wall separating me and the outside world. Words like 'immersive' and 'eco-tourism' are often overused in the travel industry, but Mashpi Lodge, a boutique hotel placed in the middle of a steamy Ecuadorian jungle, couldn't be truer of these concepts. 



After:

In [18]:
df_clean = text_cleansing(df['Texts'])

for i in df_clean:
    print(i, '/n')

the first unseeded winner of the wimbledon women s singles title marketa vondrousova has shocked the world and beaten ons jabeur vondrousova tennis wimbledon bbcsport /n
the morning sun filtered between the tree trunks of the dense mist filled chocó cloud forest as i watched colourful butterflies and vibrant tanagers flutter among the branches all from the comfort of my bed with just a glass wall separating me and the outside world words like immersive and eco tourism are often overused in the travel industry but mashpi lodge a boutique hotel placed in the middle of a steamy ecuadorian jungle couldn t be truer of these concepts  /n


## 2.2. Word Tokenize

In [9]:
word_token=[word_tokenize(i) for i in df_clean]
word_token

[['the',
  'first',
  'unseeded',
  'winner',
  'of',
  'the',
  'wimbledon',
  'women',
  's',
  'singles',
  'title',
  'marketa',
  'vondrousova',
  'has',
  'shocked',
  'the',
  'world',
  'and',
  'beaten',
  'ons',
  'jabeur',
  'vondrousova',
  'tennis',
  'wimbledon',
  'bbcsport'],
 ['the',
  'morning',
  'sun',
  'filtered',
  'between',
  'the',
  'tree',
  'trunks',
  'of',
  'the',
  'dense',
  'mist',
  'filled',
  'chocó',
  'cloud',
  'forest',
  'as',
  'i',
  'watched',
  'colourful',
  'butterflies',
  'and',
  'vibrant',
  'tanagers',
  'flutter',
  'among',
  'the',
  'branches',
  'all',
  'from',
  'the',
  'comfort',
  'of',
  'my',
  'bed',
  'with',
  'just',
  'a',
  'glass',
  'wall',
  'separating',
  'me',
  'and',
  'the',
  'outside',
  'world',
  'words',
  'like',
  'immersive',
  'and',
  'eco',
  'tourism',
  'are',
  'often',
  'overused',
  'in',
  'the',
  'travel',
  'industry',
  'but',
  'mashpi',
  'lodge',
  'a',
  'boutique',
  'hotel',
  '

In [10]:
data_enc=[]
for i in word_token:
    data_enc=data_enc+i

data_enc

['the',
 'first',
 'unseeded',
 'winner',
 'of',
 'the',
 'wimbledon',
 'women',
 's',
 'singles',
 'title',
 'marketa',
 'vondrousova',
 'has',
 'shocked',
 'the',
 'world',
 'and',
 'beaten',
 'ons',
 'jabeur',
 'vondrousova',
 'tennis',
 'wimbledon',
 'bbcsport',
 'the',
 'morning',
 'sun',
 'filtered',
 'between',
 'the',
 'tree',
 'trunks',
 'of',
 'the',
 'dense',
 'mist',
 'filled',
 'chocó',
 'cloud',
 'forest',
 'as',
 'i',
 'watched',
 'colourful',
 'butterflies',
 'and',
 'vibrant',
 'tanagers',
 'flutter',
 'among',
 'the',
 'branches',
 'all',
 'from',
 'the',
 'comfort',
 'of',
 'my',
 'bed',
 'with',
 'just',
 'a',
 'glass',
 'wall',
 'separating',
 'me',
 'and',
 'the',
 'outside',
 'world',
 'words',
 'like',
 'immersive',
 'and',
 'eco',
 'tourism',
 'are',
 'often',
 'overused',
 'in',
 'the',
 'travel',
 'industry',
 'but',
 'mashpi',
 'lodge',
 'a',
 'boutique',
 'hotel',
 'placed',
 'in',
 'the',
 'middle',
 'of',
 'a',
 'steamy',
 'ecuadorian',
 'jungle',
 'could

# 3. Text Representation

## 3.1. One Hot Enconding

In [11]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data_enc)
print(integer_encoded)

[64 26 72 78 49 64 77 80 55 58 66 42 74 31 57 64 82  3  8 51 37 74 63 77
  6 64 47 60 25 10 64 69 71 49 64 21 46 24 15 16 28  5 33 76 17 14  3 73
 62 27  2 64 12  1 29 64 18 49 48  9 79 39  0 30 75 56 44  3 64 52 82 81
 40 34  3 22 67  4 50 53 35 64 68 36 13 43 41  0 11 32 54 35 64 45 49  0
 59 23 38 20 61  7 70 49 65 19]


In [12]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


c:\Users\MSI GL65\anaconda3\envs\gpu_env\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [13]:
# invert first 3 example
for i in range(3):
    onehot_encoded_1 = onehot_encoded[i, :]
    inverted = label_encoder.inverse_transform([argmax(onehot_encoded_1)])
    print('encoded', i + 1, ':', onehot_encoded_1, '\ninverted', i + 1, ':', inverted, '\n')

encoded 1 : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
inverted 1 : ['the'] 

encoded 2 : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
inverted 2 : ['first'] 

encoded 3 : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
inverted 3 : ['unseeded'] 



## 3.2. CountVectorizer

In [14]:
vectorizer = CountVectorizer(stop_words='english')
vectorizer.fit(df_clean)
vec_sentences = vectorizer.transform(df_clean) #countvectorizes the text
print(vec_sentences.toarray())

[[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0
  0 0 1 1 0 0 0 1 1 0 0 0 0 0 1 0 2 0 0 2 1 1 0 1]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1
  1 1 0 0 1 1 1 0 0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 1]]


In [15]:
count_array = vec_sentences.toarray()
df_countVect = pd.DataFrame(data=count_array,columns = vectorizer.get_feature_names_out())
df_countVect

bbcsport  beaten  bed  boutique  branches  butterflies  chocó  cloud  \
0         1       1    0         0         0            0      0      0   
1         0       0    1         1         1            1      1      1   

   colourful  comfort  ...  unseeded  vibrant  vondrousova  wall  watched  \
0          0        0  ...         1        0            2     0        0   
1          1        1  ...         0        1            0     1        1   

   wimbledon  winner  women  words  world  
0          2       1      1      0      1  
1          0       0      0      1      1  

[2 rows x 60 columns]